/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_blur_Blur */

#ifndef _Included_com_demo_blur_Blur
#define _Included_com_demo_blur_Blur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_blur_Blur
 * Method:    blurIntArray
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_demo_blur_Blur_blurIntArray
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_demo_blur_Blur
 * Method:    blurBitMap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_demo_blur_Blur_blurBitMap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
